name: Python package

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.8
            tox-env: quality

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install virtualenv tox tox-pip-version
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "tox -e ${{ matrix.tox-env }}"
